In [1]:
import pandas as pd
import numpy as np

pd.options.display.float_format = '{:.5f}'.format

In [2]:
delivery_df = pd.read_csv("./delivery_raw.csv", sep = '\t')

delivery_df

market_id           created_at actual_delivery_time  store_id  \
0        1.00000  2015-02-06 22:24:17  2015-02-06 23:27:16      1845   
1        2.00000  2015-02-10 21:49:25  2015-02-10 22:56:29      5477   
2        3.00000  2015-01-22 20:39:28  2015-01-22 21:09:09      5477   
3        3.00000  2015-02-03 21:21:45  2015-02-03 22:13:00      5477   
4        3.00000  2015-02-15 02:40:36  2015-02-15 03:20:26      5477   
...          ...                  ...                  ...       ...   
42278    3.00000  2015-02-18 04:51:14  2015-02-18 05:19:56      2576   
42279    3.00000  2015-02-07 03:05:18  2015-02-07 04:00:19      2576   
42280    3.00000  2015-02-06 21:49:42  2015-02-06 22:14:06      2576   
42281    3.00000  2015-01-23 01:25:12  2015-01-23 01:56:08      2576   
42282    3.00000  2015-01-24 05:15:24  2015-01-24 05:50:31      2576   

      store_primary_category  order_protocol  total_items  subtotal  \
0                   american         1.00000            4      3441   
1                    mexican         2.00000            1      1900   
2                        NaN         1.00000            1      1900   
3                        NaN         1.00000            6      6900   
4                        NaN         1.00000            3      3900   
...                      ...             ...          ...       ...   
42278               american         5.00000            2      2440   
42279               american         1.00000            2      2200   
42280               american         1.00000            1       675   
42281               american         1.00000            2      1520   
42282               american         1.00000            3      4115   

       num_distinct_items  min_item_price  max_item_price  total_onshift  \
0                       4             557            1239       33.00000   
1                       1            1400            1400        1.00000   
2                       1            1900            1900        1.00000   
3                       5             600            1800        1.00000   
4                       3            1100            1600        6.00000   
...                   ...             ...             ...            ...   
42278                   2             995             995        7.00000   
42279                   2            1075            1125       31.00000   
42280                   1             675             675       12.00000   
42281                   2             595             825       17.00000   
42282                   3             595            1750       16.00000   

       total_busy  total_outstanding_orders  estimated_order_place_duration  \
0        14.00000                  21.00000                       446.00000   
1         2.00000                   2.00000                       446.00000   
2         0.00000                   0.00000                       446.00000   
3         1.00000                   2.00000                       446.00000   
4         6.00000                   9.00000                       446.00000   
...           ...                       ...                             ...   
42278     7.00000                   8.00000                       251.00000   
42279    35.00000                  42.00000                       446.00000   
42280     4.00000                   3.00000                       446.00000   
42281    14.00000                  13.00000                       446.00000   
42282         NaN                       NaN                             NaN   

       estimated_store_to_consumer_driving_duration  
0                                         861.00000  
1                                         690.00000  
2                                         690.00000  
3                                         289.00000  
4                                         650.00000  
...                                             ...  
42278                                     180.000

In [3]:
delivery_df.dtypes

market_id                                       float64
created_at                                       object
actual_delivery_time                             object
store_id                                          int64
store_primary_category                           object
order_protocol                                  float64
total_items                                       int64
subtotal                                          int64
num_distinct_items                                int64
min_item_price                                    int64
max_item_price                                    int64
total_onshift                                   float64
total_busy                                      float64
total_outstanding_orders                        float64
estimated_order_place_duration                  float64
estimated_store_to_consumer_driving_duration    float64
dtype: object

In [4]:
delivery_df.isna().sum()

market_id                                        212
created_at                                         0
actual_delivery_time                               2
store_id                                           0
store_primary_category                          1047
order_protocol                                   216
total_items                                        0
subtotal                                           0
num_distinct_items                                 0
min_item_price                                     0
max_item_price                                     0
total_onshift                                   3385
total_busy                                      3386
total_outstanding_orders                        3386
estimated_order_place_duration                     1
estimated_store_to_consumer_driving_duration     115
dtype: int64

In [5]:
delivery_df.dropna(inplace=True)
delivery_df = delivery_df.reset_index(drop=True)

In [6]:
delivery_df['created_at'] = pd.to_datetime(delivery_df['created_at'])
delivery_df['actual_delivery_time'] = pd.to_datetime(delivery_df['actual_delivery_time'])
delivery_df['delivery_duration'] = delivery_df['actual_delivery_time'] - delivery_df['created_at']
delivery_df['delivery_duration'] = delivery_df['delivery_duration'].dt.total_seconds()

delivery_df[['delivery_duration','estimated_store_to_consumer_driving_duration']]

delivery_duration  estimated_store_to_consumer_driving_duration
0             3779.00000                                     861.00000
1             4024.00000                                     690.00000
2             1586.00000                                     289.00000
3             2273.00000                                     795.00000
4             2988.00000                                     205.00000
...                  ...                                           ...
37724         2081.00000                                     323.00000
37725         1722.00000                                     180.00000
37726         3301.00000                                     579.00000
37727         1464.00000                                     362.00000
37728         1856.00000                                     116.00000

[37729 rows x 2 columns]

In [7]:
delivery_df.describe()

market_id    store_id  order_protocol  total_items    subtotal  \
count 37729.00000 37729.00000     37729.00000  37729.00000 37729.00000   
mean      2.74486  3692.44411         2.78608      3.28371  2729.00066   
std       1.31945  2069.80977         1.47987      2.64517  1848.24499   
min       1.00000    17.00000         1.00000      1.00000     0.00000   
25%       2.00000  1869.00000         1.00000      2.00000  1445.00000   
50%       2.00000  3770.00000         3.00000      3.00000  2255.00000   
75%       4.00000  5470.00000         4.00000      4.00000  3470.00000   
max       6.00000  6986.00000         7.00000     57.00000 18370.00000   

       num_distinct_items  min_item_price  max_item_price  total_onshift  \
count         37729.00000     37729.00000     37729.00000    37729.00000   
mean              2.72231       676.78772      1180.87535       44.88036   
std               1.66323       529.84642       582.01172       34.75701   
min               1.00000       -86.00000         0.00000       -2.00000   
25%               2.00000       295.00000       800.00000       17.00000   
50%               2.00000       575.00000      1095.00000       36.00000   
75%               3.00000       914.00000      1400.00000       65.00000   
max              20.00000      7475.00000      8500.00000      171.00000   

       total_busy  total_outstanding_orders  estimated_order_place_duration  \
count 37729.00000               37729.00000                     37729.00000   
mean     41.92679                  58.47878                       312.16934   
std      32.40097                  53.27095                        91.00167   
min      -1.00000                  -6.00000                         0.00000   
25%      15.00000                  17.00000                       251.00000   
50%      35.00000                  41.00000                       251.00000   
75%      63.00000                  86.00000                       446.00000   
max     154.00000                 285.00000                      1153.00000   

       estimated_store_to_consumer_driving_duration  delivery_duration  
count                                   37729.00000        37729.00000  
mean                                      548.05182         2901.62262  
std                                       219.35473         2054.32545  
min                                         0.00000          223.00000  
25%                                       387.00000         2125.00000  
50%                                       546.00000         2691.00000  
75%                                       705.00000         3429.00000  
max                                      2088.00000       332482.00000

In [8]:
delivery_df.corr()

<ipython-input-8-a9affaea5b5e>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  delivery_df.corr()


market_id  store_id  \
market_id                                       1.00000  -0.01529   
store_id                                       -0.01529   1.00000   
order_protocol                                  0.04300   0.09592   
total_items                                     0.01687  -0.00959   
subtotal                                        0.02548  -0.05935   
num_distinct_items                              0.03059  -0.03789   
min_item_price                                 -0.00013  -0.02999   
max_item_price                                  0.01632  -0.08329   
total_onshift                                   0.08553  -0.03066   
total_busy                                      0.07965  -0.02854   
total_outstanding_orders                        0.08110  -0.03699   
estimated_order_place_duration                 -0.08951  -0.02007   
estimated_store_to_consumer_driving_duration    0.02341  -0.03055   
delivery_duration                              -0.02292  -0.02671   

                                              order_protocol  total_items  \
market_id                                            0.04300      0.01687   
store_id                                             0.09592     -0.00959   
order_protocol                                       1.00000      0.03784   
total_items                                          0.03784      1.00000   
subtotal                                            -0.05960      0.57842   
num_distinct_items                                   0.00486      0.80066   
min_item_price                                      -0.08064     -0.41204   
max_item_price                                      -0.11209     -0.06434   
total_onshift                                        0.15270      0.04807   
total_busy                                           0.16111      0.04688   
total_outstanding_orders                             0.13262      0.05216   
estimated_order_place_duration                      -0.71148     -0.06608   
estimated_store_to_consumer_driving_duration         0.00564      0.02167   
delivery_duration                                   -0.05623      0.06345   

                                              subtotal  num_distinct_items  \
market_id                                      0.02548             0.03059   
store_id                                      -0.05935            -0.03789   
order_protocol                                -0.05960             0.00486   
total_items                                    0.57842             0.80066   
subtotal                                       1.00000             0.67487   
num_distinct_items                             0.67487             1.00000   
min_item_price                                 0.03349            -0.45048   
max_item_price                                 0.51050             0.03897   
total_onshift                                  0.13004             0.07393   
total_busy                                     0.12843             0.07094   
total_outstanding_orders                       0.13743             0.08012   
estimated_order_place_duration                 0.02242            -0.03796   
estimated_store_to_consumer_driving_duration   0.04529             0.03647   
delivery_duration                              0.12565             0.08710   

                                              min_item_price  max_item_price  \
market_id                                           -0.00013         0.01632   
store_id                                            -0.02999        -0.08329   
order_protocol                                      -0.08064        -0.11209   
total_items                                         -0.41204        -0.06434   
subtotal                                             0.03349         0.51050   
num_distinct_items                                  -0.45048         0.03897   
min_item_price                                       1.00000         0.52350   
max_item_price                             

In [9]:
from sklearn.preprocessing import OneHotEncoder

print(delivery_df['store_primary_category'])
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoded_df = pd.DataFrame(encoder.fit_transform(delivery_df[['store_primary_category']]))

print(encoded_df.shape)
print(delivery_df.shape)
delivery_df = pd.concat([delivery_df, encoded_df], axis = 1)

0             american
1              mexican
2               indian
3              italian
4              italian
             ...      
37724    mediterranean
37725         american
37726         american
37727         american
37728         american
Name: store_primary_category, Length: 37729, dtype: object
(37729, 65)
(37729, 17)


In [10]:
from sklearn.preprocessing import MinMaxScaler

removed_list = ['delivery_duration',
                'created_at',
                'actual_delivery_time',
                'store_primary_category',
               'estimated_store_to_consumer_driving_duration',
               'estimated_order_place_duration',
]

tot_data = delivery_df[delivery_df.columns.difference(removed_list)].to_numpy()
tot_label = delivery_df['delivery_duration'].to_numpy()
print(tot_data)
scaler = MinMaxScaler() 
scaler.fit(tot_data) 
tot_data = scaler.transform(tot_data)     


[[ 0.  0.  0. ...  4. 33. 21.]
 [ 0.  0.  0. ...  1.  1.  2.]
 [ 0.  0.  0. ...  4.  8. 18.]
 ...
 [ 0.  0.  0. ...  2. 31. 42.]
 [ 0.  0.  0. ...  1. 12.  3.]
 [ 0.  0.  0. ...  2. 17. 13.]]


In [11]:
from sklearn.model_selection import train_test_split


train_data, test_data, train_label, test_label = train_test_split(tot_data, tot_label, test_size=0.1, random_state=1000)

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer
from sklearn.linear_model import Ridge
def weighted_rmse(y_true, y_pred):
     score = np.where(y_true > y_pred, 2 * (y_true - y_pred)**2, (y_true - y_pred)**2) / np.sum(y_true < y_pred)*2
     return np.sqrt(np.mean(score))

score = make_scorer(weighted_rmse, greater_is_better=False)

grid = GridSearchCV(estimator=Ridge(), param_grid={'alpha' : [0., 1.0, 10.0]},
                      scoring=score, cv=5)
grid.fit(train_data, train_label)

GridSearchCV(cv=5, estimator=Ridge(), param_grid={'alpha': [0.0, 1.0, 10.0]},
             scoring=make_scorer(weighted_rmse, greater_is_better=False))

In [13]:
predicted_label = grid.predict(test_data)

def rmse(y_true, y_pred) :
  return np.sqrt(np.mean((y_true-y_pred) ** 2))

def cal_under_predict(y_true, y_pred) :
  return np.sum(y_true > y_pred) / len(y_true)

print(rmse(test_label, predicted_label))
print(cal_under_predict(test_label, predicted_label))

1142.0733960385467
0.4206201961304002
